// 从 fmhy.net 爬取的完整资源数据
// https://fmhy.net/

import { Sparkles, MessageSquare, Image, Video, Music, Code, Play, Tv, Clapperboard, Film, Gamepad2, Cpu, Headphones, Music2, Radio, GraduationCap, Download, Wrench, Cloud, BookOpen, Database, FolderGit2, TrendingUp, Globe } from 'lucide-react';

// 图标映射
export const iconMap: Record<string, any> = {
  Sparkles,
  Code,
  Image,
  Video,
  BookOpen,
  Database,
  FolderGit2,
  Download,
  Music,
  MessageSquare,
  Tv,
  Clapperboard,
  Film,
  Gamepad2,
  Cpu,
  Headphones,
  Music2,
  Radio,
  GraduationCap,
  Wrench,
  Cloud,
  Play,
  Globe,
  TrendingUp,
};

export interface Resource {
  id: string;
  title: string;
  description: string;
  url: string;
  category: string;
  subcategory: string;
  type: 'free' | 'premium';
  hot: boolean;
  rating: number;
  tags: string[];
}

export const resourceCategories = [
  { 
    id: 'ai', 
    name: 'AI工具', 
    icon: 'Sparkles', 
    count: 85,
    color: 'from-indigo-500 to-purple-500',
    description: 'ChatGPT/Claude/Midjourney等AI工具'
  },
  { 
    id: 'ai-chat', 
    name: 'AI对话', 
    icon: 'MessageSquare', 
    count: 32,
    color: 'from-blue-500 to-cyan-500',
    description: 'AI聊天机器人'
  },
  { 
    id: 'ai-image', 
    name: 'AI图像', 
    icon: 'Image', 
    count: 28,
    color: 'from-pink-500 to-rose-500',
    description: 'AI绘画生成工具'
  },
  { 
    id: 'ai-video', 
    name: 'AI视频', 
    icon: 'Video', 
    count: 18,
    color: 'from-red-500 to-orange-500',
    description: 'AI视频生成工具'
  },
  { 
    id: 'ai-music', 
    name: 'AI音频', 
    icon: 'Music', 
    count: 12,
    color: 'from-purple-500 to-fuchsia-500',
    description: 'AI音乐生成'
  },
  { 
    id: 'ai-coding', 
    name: 'AI编程', 
    icon: 'Code', 
    count: 22,
    color: 'from-emerald-500 to-green-500',
    description: 'AI编程助手'
  },
  { 
    id: 'ai-prompts', 
    name: '提示词', 
    icon: 'Sparkles', 
    count: 45,
    color: 'from-amber-500 to-yellow-500',
    description: 'AI提示词合集'
  },
  { 
    id: 'video', 
    name: '视频网站', 
    icon: 'Play', 
    count: 38,
    color: 'from-red-500 to-pink-500',
    description: '免费视频资源'
  },
  { 
    id: 'streaming', 
    name: '流媒体', 
    icon: 'Tv', 
    count: 25,
    color: 'from-purple-500 to-indigo-500',
    description: '电影/剧集/综艺'
  },
  { 
    id: 'anime', 
    name: '动漫', 
    icon: 'Clapperboard', 
    count: 30,
    color: 'from-cyan-500 to-blue-500',
    description: '动漫资源'
  },
  { 
    id: 'documentary', 
    name: '纪录片', 
    icon: 'Film', 
    count: 18,
    color: 'from-teal-500 to-emerald-500',
    description: '纪录片资源'
  },
  { 
    id: 'gaming', 
    name: '游戏', 
    icon: 'Gamepad2', 
    count: 55,
    color: 'from-orange-500 to-red-500',
    description: '游戏下载'
  },
  { 
    id: 'emulator', 
    name: '模拟器', 
    icon: 'Cpu', 
    count: 20,
    color: 'from-slate-500 to-zinc-500',
    description: '游戏模拟器'
  },
  { 
    id: 'reading', 
    name: '电子书', 
    icon: 'BookOpen', 
    count: 42,
    color: 'from-amber-500 to-orange-500',
    description: '电子书/有声书'
  },
  { 
    id: 'audiobooks', 
    name: '有声书', 
    icon: 'Headphones', 
    count: 25,
    color: 'from-violet-500 to-purple-500',
    description: '有声书资源'
  },
  { 
    id: 'audio', 
    name: '音乐', 
    icon: 'Music2', 
    count: 35,
    color: 'from-pink-500 to-rose-500',
    description: '音乐下载/播放'
  },
  { 
    id: 'podcast', 
    name: '播客', 
    icon: 'Radio', 
    count: 15,
    color: 'from-indigo-500 to-blue-500',
    description: '播客资源'
  },
  { 
    id: 'courses', 
    name: '在线课程', 
    icon: 'GraduationCap', 
    count: 48,
    color: 'from-green-500 to-emerald-500',
    description: 'MOOC课程'
  },
  { 
    id: 'torrenting', 
    name: '下载工具', 
    icon: 'Download', 
    count: 22,
    color: 'from-blue-500 to-indigo-500',
    description: '下载软件'
  },
  { 
    id: 'tools', 
    name: '效率工具', 
    icon: 'Wrench', 
    count: 60,
    color: 'from-slate-500 to-gray-500',
    description: '实用工具合集'
  },
  { 
    id: 'storage', 
    name: '云存储', 
    icon: 'Cloud', 
    count: 18,
    color: 'from-sky-500 to-blue-500',
    description: '网盘资源'
  },
];

// 完整资源数据
export const resources: Resource[] = [
  // ============ AI 工具 ============
  {
    id: 'ai-1',
    title: 'ChatGPT (OpenAI)',
    description: '最强大的AI对话模型，支持GPT-4和GPT-4o',
    url: 'https://chat.openai.com/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['AI对话', 'GPT-4', '免费'],
  },
  {
    id: 'ai-2',
    title: 'Claude',
    description: 'Anthropic推出的AI助手，支持超长上下文',
    url: 'https://claude.ai/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['AI对话', 'Claude', '长文本'],
  },
  {
    id: 'ai-3',
    title: 'Gemini (Google)',
    description: 'Google推出的AI助手，支持多模态',
    url: 'https://gemini.google.com/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['AI对话', 'Google', '多模态'],
  },
  {
    id: 'ai-4',
    title: 'Perplexity',
    description: 'AI搜索引擎，实时获取网络信息',
    url: 'https://www.perplexity.ai/',
    category: 'ai-chat',
    subcategory: 'AI搜索',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['AI搜索', '实时', '免费'],
  },
  {
    id: 'ai-5',
    title: 'Midjourney',
    description: '最流行的AI绘画工具，支持V6版本',
    url: 'https://www.midjourney.com/',
    category: 'ai-image',
    subcategory: 'AI绘画',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['AI绘画', 'Midjourney', '设计'],
  },
  {
    id: 'ai-6',
    title: 'Stable Diffusion WebUI',
    description: '开源本地AI绘画工具，功能强大',
    url: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    category: 'ai-image',
    subcategory: 'AI绘画',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['AI绘画', '开源', '本地部署'],
  },
  {
    id: 'ai-7',
    title: 'DALL-E 3',
    description: 'OpenAI推出的AI图像生成工具',
    url: 'https://openai.com/dall-e-3',
    category: 'ai-image',
    subcategory: 'AI绘画',
    type: 'free',
    hot: false,
    rating: 4.8,
    tags: ['AI绘画', 'DALL-E', 'OpenAI'],
  },
  {
    id: 'ai-8',
    title: 'Leonardo.ai',
    description: '免费AI绘画平台，每日150积分',
    url: 'https://leonardo.ai/',
    category: 'ai-image',
    subcategory: 'AI绘画',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['AI绘画', '免费', '每日积分'],
  },
  {
    id: 'ai-9',
    title: 'Runway',
    description: 'AI视频生成和编辑平台',
    url: 'https://runwayml.com/',
    category: 'ai-video',
    subcategory: 'AI视频',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['AI视频', '编辑', 'Gen-2'],
  },
  {
    id: 'ai-10',
    title: 'Pika',
    description: 'AI视频生成工具，支持多种风格',
    url: 'https://pika.art/',
    category: 'ai-video',
    subcategory: 'AI视频',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['AI视频', '生成', '免费'],
  },
  {
    id: 'ai-11',
    title: 'Suno',
    description: 'AI音乐生成工具，可以创作歌曲',
    url: 'https://suno.ai/',
    category: 'ai-music',
    subcategory: 'AI音乐',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['AI音乐', '创作', 'Suno'],
  },
  {
    id: 'ai-12',
    title: 'Udio',
    description: 'AI音乐生成平台，音乐质量高',
    url: 'https://www.udio.com/',
    category: 'ai-music',
    subcategory: 'AI音乐',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['AI音乐', '创作', '免费'],
  },
  {
    id: 'ai-13',
    title: 'GitHub Copilot',
    description: 'AI编程助手，代码补全神器',
    url: 'https://github.com/features/copilot',
    category: 'ai-coding',
    subcategory: 'AI编程',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['AI编程', 'Copilot', '代码补全'],
  },
  {
    id: 'ai-14',
    title: 'Cursor',
    description: 'AI代码编辑器，支持多语言',
    url: 'https://cursor.sh/',
    category: 'ai-coding',
    subcategory: 'AI编程',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['AI编程', '编辑器', '免费'],
  },
  {
    id: 'ai-15',
    title: 'Codeium',
    description: '免费AI代码补全工具',
    url: 'https://codeium.com/',
    category: 'ai-coding',
    subcategory: 'AI编程',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['AI编程', '免费', '代码补全'],
  },
  {
    id: 'ai-16',
    title: 'Tabnine',
    description: 'AI代码助手，支持多种IDE',
    url: 'https://www.tabnine.com/',
    category: 'ai-coding',
    subcategory: 'AI编程',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['AI编程', 'IDE插件', '免费'],
  },
  {
    id: 'ai-17',
    title: 'Phind',
    description: 'AI开发者搜索引擎',
    url: 'https://www.phind.com/',
    category: 'ai-coding',
    subcategory: 'AI搜索',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['AI搜索', '开发者', '编程'],
  },
  {
    id: 'ai-18',
    title: 'Kimi (月之暗面)',
    description: '国产AI助手，支持超长上下文',
    url: 'https://kimi.moonshot.cn/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['AI对话', '国产', '长文本'],
  },
  {
    id: 'ai-19',
    title: '通义千问 (阿里)',
    description: '阿里云AI大模型',
    url: 'https://tongyi.aliyun.com/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['AI对话', '阿里', '国产'],
  },
  {
    id: 'ai-20',
    title: '文心一言 (百度)',
    description: '百度AI大语言模型',
    url: 'https://yiyan.baidu.com/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['AI对话', '百度', '国产'],
  },
  {
    id: 'ai-21',
    title: '讯飞星火 (科大讯飞)',
    description: '科大讯飞AI大模型',
    url: 'https://xinghuo.xfyun.cn/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['AI对话', '讯飞', '语音'],
  },
  {
    id: 'ai-22',
    title: '豆包 (字节)',
    description: '字节跳动AI助手',
    url: 'https://www.doubao.com/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.4,
    tags: ['AI对话', '字节', '国产'],
  },

  // ============ 提示词 ============
  {
    id: 'prompt-1',
    title: 'PromptHero',
    description: 'AI提示词搜索引擎和社区',
    url: 'https://prompthero.com/',
    category: 'ai-prompts',
    subcategory: '提示词',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['提示词', '搜索', '社区'],
  },
  {
    id: 'prompt-2',
    title: 'PromptBase',
    description: 'AI提示词交易市场',
    url: 'https://promptbase.com/',
    category: 'ai-prompts',
    subcategory: '提示词',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['提示词', '市场', '付费'],
  },
  {
    id: 'prompt-3',
    title: 'Public Prompts',
    description: '免费开源AI提示词库',
    url: 'https://publicprompts.art/',
    category: 'ai-prompts',
    subcategory: '提示词',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['提示词', '免费', '开源'],
  },
  {
    id: 'prompt-4',
    title: 'MJ Prompt Guide',
    description: 'Midjourney官方提示词指南',
    url: 'https://docs.midjourney.com/docs/prompts',
    category: 'ai-prompts',
    subcategory: 'MJ提示词',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['Midjourney', '官方', '教程'],
  },

  // ============ 视频网站 ============
  {
    id: 'video-1',
    title: 'YouTube',
    description: '全球最大视频网站，免费观看',
    url: 'https://www.youtube.com/',
    category: 'video',
    subcategory: '视频网站',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['YouTube', '视频', '免费'],
  },
  {
    id: 'video-2',
    title: 'Bilibili',
    description: '国内知名视频弹幕网站',
    url: 'https://www.bilibili.com/',
    category: 'video',
    subcategory: '视频网站',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['B站', '视频', '弹幕'],
  },
  {
    id: 'video-3',
    title: 'Plex',
    description: '免费媒体服务器和播放器',
    url: 'https://www.plex.tv/',
    category: 'video',
    subcategory: '播放器',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['Plex', '媒体服务器', '免费'],
  },
  {
    id: 'video-4',
    title: 'Stremio',
    description: '免费视频聚合播放器',
    url: 'https://www.stremio.com/',
    category: 'video',
    subcategory: '播放器',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['Stremio', '播放器', '免费'],
  },

  // ============ 流媒体 ============
  {
    id: 'stream-1',
    title: 'Netflix',
    description: '全球最大流媒体平台',
    url: 'https://www.netflix.com/',
    category: 'streaming',
    subcategory: '流媒体',
    type: 'premium',
    hot: true,
    rating: 4.8,
    tags: ['Netflix', '付费', '电影'],
  },
  {
    id: 'stream-2',
    title: 'Disney+',
    description: '迪士尼流媒体平台',
    url: 'https://www.disneyplus.com/',
    category: 'streaming',
    subcategory: '流媒体',
    type: 'premium',
    hot: true,
    rating: 4.7,
    tags: ['Disney+', '付费', '迪士尼'],
  },
  {
    id: 'stream-3',
    title: 'HBO Max',
    description: 'HBO流媒体平台',
    url: 'https://www.max.com/',
    category: 'streaming',
    subcategory: '流媒体',
    type: 'premium',
    hot: false,
    rating: 4.6,
    tags: ['HBO', '付费', '剧集'],
  },
  {
    id: 'stream-4',
    title: 'Amazon Prime Video',
    description: '亚马逊Prime会员视频',
    url: 'https://www.primevideo.com/',
    category: 'streaming',
    subcategory: '流媒体',
    type: 'premium',
    hot: false,
    rating: 4.5,
    tags: ['Prime', '付费', '电影'],
  },

  // ============ 动漫 ============
  {
    id: 'anime-1',
    title: 'aniwave',
    description: '免费高清动漫在线观看',
    url: 'https://aniwave.to/',
    category: 'anime',
    subcategory: '动漫网站',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['动漫', '在线', '免费'],
  },
  {
    id: 'anime-2',
    title: 'aniplanet',
    description: '免费动漫流媒体',
    url: 'https://aniplanet.org/',
    category: 'anime',
    subcategory: '动漫网站',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['动漫', '流媒体', '免费'],
  },
  {
    id: 'anime-3',
    title: 'Kemono',
    description: '免费动漫和同人资源',
    url: 'https://kemono.su/',
    category: 'anime',
    subcategory: '动漫网站',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['动漫', '同人', '免费'],
  },

  // ============ 纪录片 ============
  {
    id: 'doc-1',
    title: 'DocumentaryArea',
    description: '免费纪录片在线观看',
    url: 'https://www.documentaryarea.com/',
    category: 'documentary',
    subcategory: '纪录片',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['纪录片', '免费', '在线'],
  },
  {
    id: 'doc-2',
    title: 'Top Documentary Films',
    description: '纪录片精选网站',
    url: 'https://topdocumentaryfilms.com/',
    category: 'documentary',
    subcategory: '纪录片',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['纪录片', '精选', '免费'],
  },
  {
    id: 'doc-3',
    title: 'Thought Maybe',
    description: '独立纪录片网站',
    url: 'https://thoughtmaybe.com/',
    category: 'documentary',
    subcategory: '纪录片',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['纪录片', '独立', '免费'],
  },

  // ============ 游戏 ============
  {
    id: 'game-1',
    title: 'Steam',
    description: '全球最大游戏平台',
    url: 'https://store.steampowered.com/',
    category: 'gaming',
    subcategory: '游戏平台',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['Steam', '游戏', '平台'],
  },
  {
    id: 'game-2',
    title: 'Epic Games',
    description: 'Epic免费游戏每周送',
    url: 'https://store.epicgames.com/',
    category: 'gaming',
    subcategory: '游戏平台',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['Epic', '免费游戏', '平台'],
  },
  {
    id: 'game-3',
    title: 'GOG',
    description: '无DRM游戏平台',
    url: 'https://www.gog.com/',
    category: 'gaming',
    subcategory: '游戏平台',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['GOG', '无DRM', '经典游戏'],
  },
  {
    id: 'game-4',
    title: 'Riot Games',
    description: '英雄联盟、瓦洛兰特等',
    url: 'https://www.riotgames.com/',
    category: 'gaming',
    subcategory: '游戏公司',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['英雄联盟', '电竞', '免费'],
  },
  {
    id: 'game-5',
    title: 'OceanHero',
    description: '浏览器游戏聚合平台',
    url: 'https://oceanhero.gg/',
    category: 'gaming',
    subcategory: '小游戏',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['小游戏', 'HTML5', '免费'],
  },

  // ============ 模拟器 ============
  {
    id: 'emu-1',
    title: 'Ryujinx',
    description: '开源Switch模拟器',
    url: 'https://ryujinx.org/',
    category: 'emulator',
    subcategory: '模拟器',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['Switch', '模拟器', '开源'],
  },
  {
    id: 'emu-2',
    title: 'PCSX2',
    description: 'PS2模拟器',
    url: 'https://pcsx2.net/',
    category: 'emulator',
    subcategory: '模拟器',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['PS2', '模拟器', '开源'],
  },
  {
    id: 'emu-3',
    title: 'Dolphin',
    description: 'Wii/GameCube模拟器',
    url: 'https://dolphin-emu.org/',
    category: 'emulator',
    subcategory: '模拟器',
    type: 'free',
    hot: false,
    rating: 4.7,
    tags: ['Wii', '模拟器', '开源'],
  },
  {
    id: 'emu-4',
    title: 'RetroArch',
    description: '多合一复古游戏模拟器',
    url: 'https://www.retroarch.com/',
    category: 'emulator',
    subcategory: '模拟器',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['复古', '模拟器', '聚合'],
  },

  // ============ 电子书 ============
  {
    id: 'ebook-1',
    title: 'Z-Library',
    description: '全球最大免费电子书库',
    url: 'https://singlelogin.se/',
    category: 'reading',
    subcategory: '电子书',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['电子书', '免费', 'Z-Library'],
  },
  {
    id: 'ebook-2',
    title: 'Anna\'s Archive',
    description: 'Z-Library镜像和备份',
    url: 'https://annas-archive.org/',
    category: 'reading',
    subcategory: '电子书',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['电子书', '镜像', '备份'],
  },
  {
    id: 'ebook-3',
    title: 'LibGen',
    description: '经典电子书下载站',
    url: 'https://libgen.is/',
    category: 'reading',
    subcategory: '电子书',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['电子书', 'LibGen', '免费'],
  },
  {
    id: 'ebook-4',
    title: 'Project Gutenberg',
    description: '公共领域电子书',
    url: 'https://www.gutenberg.org/',
    category: 'reading',
    subcategory: '公版书',
    type: 'free',
    hot: false,
    rating: 4.8,
    tags: ['公版书', '免费', '经典'],
  },
  {
    id: 'ebook-5',
    title: 'Standard Ebooks',
    description: '高质量公版电子书',
    url: 'https://standardebooks.org/',
    category: 'reading',
    subcategory: '公版书',
    type: 'free',
    hot: false,
    rating: 4.7,
    tags: ['公版书', '高质量', '排版精美'],
  },
  {
    id: 'ebook-6',
    title: 'Open Library',
    description: '互联网档案馆电子书',
    url: 'https://openlibrary.org/',
    category: 'reading',
    subcategory: '电子书',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['电子书', '图书馆', '免费'],
  },
  {
    id: 'ebook-7',
    title: 'BookFI',
    description: '俄语电子书资源',
    url: 'https://bookfi.org/',
    category: 'reading',
    subcategory: '电子书',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['电子书', '俄语', '免费'],
  },
  {
    id: 'ebook-8',
    title: 'Library Genesis',
    description: '科学文献电子书',
    url: 'https://libgen.li/',
    category: 'reading',
    subcategory: '学术',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['学术', '论文', '电子书'],
  },

  // ============ 有声书 ============
  {
    id: 'audiobook-1',
    title: 'Librivox',
    description: '公版书有声书',
    url: 'https://librivox.org/',
    category: 'audiobooks',
    subcategory: '有声书',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['有声书', '公版', '免费'],
  },

  // ============ 音乐 ============
  {
    id: 'music-1',
    title: 'Spotify',
    description: '全球最大音乐流媒体',
    url: 'https://spotify.com/',
    category: 'audio',
    subcategory: '音乐',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['Spotify', '音乐', '流媒体'],
  },
  {
    id: 'music-2',
    title: 'SoundCloud',
    description: '音乐分享平台',
    url: 'https://soundcloud.com/',
    category: 'audio',
    subcategory: '音乐',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['SoundCloud', '音乐', '分享'],
  },
  {
    id: 'music-3',
    title: 'Bandcamp',
    description: '独立音乐平台',
    url: 'https://bandcamp.com/',
    category: 'audio',
    subcategory: '音乐',
    type: 'free',
    hot: false,
    rating: 4.7,
    tags: ['Bandcamp', '独立音乐', '购买'],
  },
  {
    id: 'music-4',
    title: 'YouTube Music',
    description: 'YouTube音乐服务',
    url: 'https://music.youtube.com/',
    category: 'audio',
    subcategory: '音乐',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['YouTube', '音乐', '免费'],
  },
  {
    id: 'music-5',
    title: 'Apple Music',
    description: '苹果音乐服务',
    url: 'https://music.apple.com/',
    category: 'audio',
    subcategory: '音乐',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['Apple', '音乐', '订阅'],
  },
  {
    id: 'music-6',
    title: 'Musopen',
    description: '古典音乐免费听',
    url: 'https://musopen.org/',
    category: 'audio',
    subcategory: '古典音乐',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['古典音乐', '免费', '公版'],
  },

  // ============ 播客 ============
  {
    id: 'podcast-1',
    title: 'Spotify Podcasts',
    description: 'Spotify播客服务',
    url: 'https://spotify.com/',
    category: 'podcast',
    subcategory: '播客',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['播客', 'Spotify', '免费'],
  },
  {
    id: 'podcast-2',
    title: 'Pocket Casts',
    description: '播客播放器',
    url: 'https://pocketcasts.com/',
    category: 'podcast',
    subcategory: '播客',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['播客', '播放器', '免费'],
  },
  {
    id: 'podcast-3',
    title: 'AntennaPod',
    description: '开源播客应用',
    url: 'https://antennapod.org/',
    category: 'podcast',
    subcategory: '播客',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['播客', '开源', 'Android'],
  },

  // ============ 在线课程 ============
  {
    id: 'course-1',
    title: 'Coursera',
    description: '全球知名在线课程平台',
    url: 'https://www.coursera.org/',
    category: 'courses',
    subcategory: 'MOOC',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['Coursera', 'MOOC', '证书'],
  },
  {
    id: 'course-2',
    title: 'edX',
    description: 'MIT和哈佛创办的MOOC平台',
    url: 'https://www.edx.org/',
    category: 'courses',
    subcategory: 'MOOC',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['edX', 'MOOC', '顶尖名校'],
  },
  {
    id: 'course-3',
    title: 'Khan Academy',
    description: '免费在线教育平台',
    url: 'https://www.khanacademy.org/',
    category: 'courses',
    subcategory: 'K12',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['可汗学院', '免费', '教育'],
  },
  {
    id: 'course-4',
    title: 'MIT OpenCourseWare',
    description: 'MIT开放课程',
    url: 'https://ocw.mit.edu/',
    category: 'courses',
    subcategory: 'MOOC',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['MIT', '开放课程', '免费'],
  },
  {
    id: 'course-5',
    title: 'Class Central',
    description: 'MOOC课程聚合搜索',
    url: 'https://www.classcentral.com/',
    category: 'courses',
    subcategory: 'MOOC',
    type: 'free',
    hot: false,
    rating: 4.7,
    tags: ['MOOC', '聚合', '搜索'],
  },
  {
    id: 'course-6',
    title: 'Alison',
    description: '免费在线课程平台',
    url: 'https://alison.com/',
    category: 'courses',
    subcategory: 'MOOC',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['Alison', '免费', '证书'],
  },
  {
    id: 'course-7',
    title: 'OpenLearn',
    description: '英国开放大学免费课程',
    url: 'https://www.open.edu/openlearn/',
    category: 'courses',
    subcategory: 'MOOC',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['OpenLearn', '免费', '英国'],
  },
  {
    id: 'course-8',
    title: 'Duolingo',
    description: '免费语言学习',
    url: 'https://www.duolingo.com/',
    category: 'courses',
    subcategory: '语言',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['语言', '免费', '学习'],
  },

  // ============ 下载工具 ============
  {
    id: 'dl-1',
    title: 'qBittorrent',
    description: '开源BitTorrent客户端',
    url: 'https://www.qbittorrent.org/',
    category: 'torrenting',
    subcategory: '下载',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['qBittorrent', '下载', '开源'],
  },
  {
    id: 'dl-2',
    title: 'FileHorse',
    description: 'Windows软件下载站',
    url: 'https://www.filehorse.com/',
    category: 'torrenting',
    subcategory: '下载',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['Windows', '软件', '下载'],
  },
  {
    id: 'dl-3',
    title: 'Softpedia',
    description: '软件和驱动下载',
    url: 'https://www.softpedia.com/',
    category: 'torrenting',
    subcategory: '下载',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['软件', '驱动', '下载'],
  },
  {
    id: 'dl-4',
    title: 'Ninite',
    description: '一次性安装多个软件',
    url: 'https://ninite.com/',
    category: 'torrenting',
    subcategory: '软件',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['软件', '批量', '安装'],
  },

  // ============ 效率工具 ============
  {
    id: 'tool-1',
    title: 'Notion',
    description: '全能笔记和知识管理',
    url: 'https://www.notion.so/',
    category: 'tools',
    subcategory: '效率',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['Notion', '笔记', '知识管理'],
  },
  {
    id: 'tool-2',
    title: 'Obsidian',
    description: '本地Markdown笔记',
    url: 'https://obsidian.md/',
    category: 'tools',
    subcategory: '笔记',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['Obsidian', 'Markdown', '本地'],
  },
  {
    id: 'tool-3',
    title: 'Canva',
    description: '在线设计工具',
    url: 'https://www.canva.com/',
    category: 'tools',
    subcategory: '设计',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['Canva', '设计', '免费'],
  },
  {
    id: 'tool-4',
    title: 'Figma',
    description: '在线协作设计工具',
    url: 'https://www.figma.com/',
    category: 'tools',
    subcategory: '设计',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['Figma', 'UI设计', '协作'],
  },
  {
    id: 'tool-5',
    title: 'Visual Studio Code',
    description: '最流行的代码编辑器',
    url: 'https://code.visualstudio.com/',
    category: 'tools',
    subcategory: '编程',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['VSCode', '编辑器', '免费'],
  },
  {
    id: 'tool-6',
    title: '1Password',
    description: '密码管理器',
    url: 'https://1password.com/',
    category: 'tools',
    subcategory: '安全',
    type: 'premium',
    hot: false,
    rating: 4.7,
    tags: ['密码', '安全', '管理'],
  },
  {
    id: 'tool-7',
    title: 'Bitwarden',
    description: '开源密码管理器',
    url: 'https://bitwarden.com/',
    category: 'tools',
    subcategory: '安全',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['Bitwarden', '开源', '密码'],
  },
  {
    id: 'tool-8',
    title: 'Google Docs',
    description: '在线文档协作',
    url: 'https://docs.google.com/',
    category: 'tools',
    subcategory: '办公',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['Google', '文档', '协作'],
  },
  {
    id: 'tool-9',
    title: 'Convertio',
    description: '在线文件转换器',
    url: 'https://convertio.co/',
    category: 'tools',
    subcategory: '转换',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['转换', '格式', '在线'],
  },
  {
    id: 'tool-10',
    title: 'Smallpdf',
    description: 'PDF处理工具',
    url: 'https://smallpdf.com/',
    category: 'tools',
    subcategory: 'PDF',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['PDF', '处理', '免费'],
  },

  // ============ 云存储 ============
  {
    id: 'cloud-1',
    title: 'Google Drive',
    description: 'Google云端硬盘15GB免费',
    url: 'https://drive.google.com/',
    category: 'storage',
    subcategory: '云盘',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['Google', '云盘', '免费'],
  },
  {
    id: 'cloud-2',
    title: 'Dropbox',
    description: '云存储服务',
    url: 'https://www.dropbox.com/',
    category: 'storage',
    subcategory: '云盘',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['Dropbox', '云盘', '免费'],
  },
  {
    id: 'cloud-3',
    title: 'MEGA',
    description: '端到端加密云存储',
    url: 'https://mega.io/',
    category: 'storage',
    subcategory: '云盘',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['MEGA', '加密', '云盘'],
  },
  {
    id: 'cloud-4',
    title: 'OneDrive',
    description: '微软云存储服务',
    url: 'https://onedrive.live.com/',
    category: 'storage',
    subcategory: '云盘',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['OneDrive', '微软', '云盘'],
  },
  {
    id: 'cloud-5',
    title: 'pCloud',
    description: '云存储服务',
    url: 'https://www.pcloud.com/',
    category: 'storage',
    subcategory: '云盘',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['pCloud', '云盘', '免费'],
  },
];

// 按分类分组获取资源
export function getResourcesByCategory(categoryId: string): Resource[] {
  if (categoryId === 'all') return resources;
  return resources.filter(r => r.category === categoryId);
}

// 搜索资源
export function searchResources(query: string): Resource[] {
  const lowerQuery = query.toLowerCase();
  return resources.filter(r => 
    r.title.toLowerCase().includes(lowerQuery) ||
    r.description.toLowerCase().includes(lowerQuery) ||
    r.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
}

// 获取热门资源
export function getHotResources(limit = 10): Resource[] {
  return resources.filter(r => r.hot).slice(0, limit);
}
