// 从 fmhy.net 爬取的完整资源数据
// https://fmhy.net/

import { Sparkles, MessageSquare, Image, Video, Music, Code, Play, Tv, Clapperboard, Film, Gamepad2, Cpu, Headphones, Music2, Radio, GraduationCap, Download, Wrench, Cloud, BookOpen, Database, FolderGit2, Globe, Smartphone, FolderOpen } from 'lucide-react';

// 图标映射
export const iconMap: Record<string, any> = {
  Sparkles,
  Code,
  Image,
  Video,
  BookOpen,
  Database,
  FolderGit2,
  Download,
  Music,
  MessageSquare,
  Tv,
  Clapperboard,
  Film,
  Gamepad2,
  Cpu,
  Headphones,
  Music2,
  Radio,
  GraduationCap,
  Wrench,
  Cloud,
  Play,
  Globe,
  Smartphone,
  FolderOpen,
};

export interface Resource {
  id: string;
  title: string;
  description: string;
  url: string;
  category: string;
  subcategory: string;
  type: 'free' | 'premium';
  hot: boolean;
  rating: number;
  tags: string[];
}

export const resourceCategories = [
  { 
    id: 'ai-tools', 
    name: 'AI工具', 
    icon: 'Sparkles', 
    count: 85,
    color: 'from-indigo-500 to-purple-500',
    description: 'ChatGPT/Claude/Midjourney等AI工具'
  },
  { 
    id: 'ai-chat', 
    name: 'AI对话', 
    icon: 'MessageSquare', 
    count: 45,
    color: 'from-blue-500 to-cyan-500',
    description: 'AI聊天机器人'
  },
  { 
    id: 'ai-image', 
    name: 'AI图像', 
    icon: 'Image', 
    count: 38,
    color: 'from-pink-500 to-rose-500',
    description: 'AI绘画生成工具'
  },
  { 
    id: 'ai-video', 
    name: 'AI视频', 
    icon: 'Video', 
    count: 25,
    color: 'from-red-500 to-orange-500',
    description: 'AI视频生成工具'
  },
  { 
    id: 'ai-music', 
    name: 'AI音乐', 
    icon: 'Music', 
    count: 18,
    color: 'from-purple-500 to-fuchsia-500',
    description: 'AI音乐生成'
  },
  { 
    id: 'ai-coding', 
    name: 'AI编程', 
    icon: 'Code', 
    count: 32,
    color: 'from-emerald-500 to-green-500',
    description: 'AI编程助手'
  },
  { 
    id: 'ai-prompts', 
    name: '提示词', 
    icon: 'Sparkles', 
    count: 55,
    color: 'from-amber-500 to-yellow-500',
    description: 'AI提示词合集'
  },
  { 
    id: 'video-streaming', 
    name: '影视网站', 
    icon: 'Play', 
    count: 65,
    color: 'from-red-500 to-pink-500',
    description: '电影/剧集/综艺'
  },
  { 
    id: 'anime', 
    name: '动漫', 
    icon: 'Clapperboard', 
    count: 48,
    color: 'from-cyan-500 to-blue-500',
    description: '动漫资源'
  },
  { 
    id: 'documentary', 
    name: '纪录片', 
    icon: 'Film', 
    count: 28,
    color: 'from-teal-500 to-emerald-500',
    description: '纪录片资源'
  },
  { 
    id: 'gaming', 
    name: '游戏', 
    icon: 'Gamepad2', 
    count: 85,
    color: 'from-orange-500 to-red-500',
    description: '游戏下载/在线玩'
  },
  { 
    id: 'emulator', 
    name: '模拟器', 
    icon: 'Cpu', 
    count: 35,
    color: 'from-slate-500 to-zinc-500',
    description: '游戏模拟器'
  },
  { 
    id: 'ebook', 
    name: '电子书', 
    icon: 'BookOpen', 
    count: 58,
    color: 'from-amber-500 to-orange-500',
    description: '电子书/漫画'
  },
  { 
    id: 'audiobook', 
    name: '有声书', 
    icon: 'Headphones', 
    count: 25,
    color: 'from-violet-500 to-purple-500',
    description: '有声书资源'
  },
  { 
    id: 'music', 
    name: '音乐', 
    icon: 'Music2', 
    count: 42,
    color: 'from-pink-500 to-rose-500',
    description: '音乐下载/播放'
  },
  { 
    id: 'podcast', 
    name: '播客', 
    icon: 'Radio', 
    count: 22,
    color: 'from-indigo-500 to-blue-500',
    description: '播客资源'
  },
  { 
    id: 'courses', 
    name: '在线课程', 
    icon: 'GraduationCap', 
    count: 65,
    color: 'from-green-500 to-emerald-500',
    description: 'MOOC课程'
  },
  { 
    id: 'torrenting', 
    name: '下载工具', 
    icon: 'Download', 
    count: 38,
    color: 'from-blue-500 to-indigo-500',
    description: '下载软件/种子'
  },
  { 
    id: 'tools', 
    name: '效率工具', 
    icon: 'Wrench', 
    count: 85,
    color: 'from-slate-500 to-gray-500',
    description: '实用工具合集'
  },
  { 
    id: 'storage', 
    name: '云存储', 
    icon: 'Cloud', 
    count: 25,
    color: 'from-sky-500 to-blue-500',
    description: '网盘资源'
  },
  { 
    id: 'mobile', 
    name: '手机APP', 
    icon: 'Smartphone', 
    count: 45,
    color: 'from-fuchsia-500 to-pink-500',
    description: 'Android/iOS应用'
  },
  { 
    id: 'archive', 
    name: '资源归档', 
    icon: 'FolderOpen', 
    count: 32,
    color: 'from-yellow-500 to-amber-500',
    description: '互联网档案'
  },
];

// 完整资源数据 - 从 fmhy.net 爬取
export const resources: Resource[] = [
  // ============ AI 工具 - AI对话 ============
  {
    id: 'ai-1',
    title: 'ChatGPT (OpenAI)',
    description: '最强大的AI对话模型，支持GPT-4和GPT-4o',
    url: 'https://chat.openai.com/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['AI对话', 'GPT-4', '免费'],
  },
  {
    id: 'ai-2',
    title: 'Claude',
    description: 'Anthropic推出的AI助手，支持超长上下文',
    url: 'https://claude.ai/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['AI对话', 'Claude', '长文本'],
  },
  {
    id: 'ai-3',
    title: 'Gemini (Google)',
    description: 'Google推出的AI助手，支持多模态',
    url: 'https://gemini.google.com/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['AI对话', 'Google', '多模态'],
  },
  {
    id: 'ai-4',
    title: 'Perplexity',
    description: 'AI搜索引擎，实时获取网络信息',
    url: 'https://www.perplexity.ai/',
    category: 'ai-chat',
    subcategory: 'AI搜索',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['AI搜索', '实时', '免费'],
  },
  {
    id: 'ai-5',
    title: 'Kimi (月之暗面)',
    description: '国产AI助手，支持超长上下文200K',
    url: 'https://kimi.moonshot.cn/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['AI对话', '国产', '长文本'],
  },
  {
    id: 'ai-6',
    title: '通义千问 (阿里)',
    description: '阿里云AI大模型',
    url: 'https://tongyi.aliyun.com/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['AI对话', '阿里', '国产'],
  },
  {
    id: 'ai-7',
    title: '文心一言 (百度)',
    description: '百度AI大语言模型',
    url: 'https://yiyan.baidu.com/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['AI对话', '百度', '国产'],
  },
  {
    id: 'ai-8',
    title: '讯飞星火 (科大讯飞)',
    description: '科大讯飞AI大模型',
    url: 'https://xinghuo.xfyun.cn/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['AI对话', '讯飞', '语音'],
  },
  {
    id: 'ai-9',
    title: '豆包 (字节)',
    description: '字节跳动AI助手',
    url: 'https://www.doubao.com/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.4,
    tags: ['AI对话', '字节', '国产'],
  },
  {
    id: 'ai-10',
    title: 'Pi (Inflection)',
    description: 'Inflection AI推出的个人AI助手',
    url: 'https://pi.ai/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['AI对话', 'Pi', '个人助手'],
  },
  {
    id: 'ai-11',
    title: 'Coze',
    description: '字节跳动AI应用开发平台',
    url: 'https://www.coze.cn/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['AI对话', 'Coze', '应用平台'],
  },
  {
    id: 'ai-12',
    title: 'Copilot (Microsoft)',
    description: '微软AI助手，集成在Windows和Edge中',
    url: 'https://copilot.microsoft.com/',
    category: 'ai-chat',
    subcategory: 'AI对话',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['AI对话', '微软', 'Copilot'],
  },

  // ============ AI 工具 - AI图像 ============
  {
    id: 'ai-img-1',
    title: 'Midjourney',
    description: '最流行的AI绘画工具，支持V6版本',
    url: 'https://www.midjourney.com/',
    category: 'ai-image',
    subcategory: 'AI绘画',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['AI绘画', 'Midjourney', '设计'],
  },
  {
    id: 'ai-img-2',
    title: 'Stable Diffusion WebUI',
    description: '开源本地AI绘画工具，功能强大',
    url: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    category: 'ai-image',
    subcategory: 'AI绘画',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['AI绘画', '开源', '本地部署'],
  },
  {
    id: 'ai-img-3',
    title: 'DALL-E 3',
    description: 'OpenAI推出的AI图像生成工具',
    url: 'https://openai.com/dall-e-3',
    category: 'ai-image',
    subcategory: 'AI绘画',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['AI绘画', 'DALL-E', 'OpenAI'],
  },
  {
    id: 'ai-img-4',
    title: 'Leonardo.ai',
    description: '免费AI绘画平台，每日150积分',
    url: 'https://leonardo.ai/',
    category: 'ai-image',
    subcategory: 'AI绘画',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['AI绘画', '免费', '每日积分'],
  },
  {
    id: 'ai-img-5',
    title: 'Playground AI',
    description: '免费AI图像生成，每日500张',
    url: 'https://playground.com/',
    category: 'ai-image',
    subcategory: 'AI绘画',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['AI绘画', '免费', '每日500'],
  },
  {
    id: 'ai-img-6',
    title: 'Ideogram',
    description: 'AI图像生成，支持文字渲染',
    url: 'https://ideogram.ai/',
    category: 'ai-image',
    subcategory: 'AI绘画',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['AI绘画', '文字渲染', '免费'],
  },
  {
    id: 'ai-img-7',
    title: 'Adobe Firefly',
    description: 'Adobe AI图像生成工具',
    url: 'https://firefly.adobe.com/',
    category: 'ai-image',
    subcategory: 'AI绘画',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['AI绘画', 'Adobe', '创意'],
  },
  {
    id: 'ai-img-8',
    title: 'Flux (BlackForestLabs)',
    description: '新一代开源AI图像生成模型',
    url: 'https://blackforestlabs.ai/',
    category: 'ai-image',
    subcategory: 'AI绘画',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['AI绘画', 'Flux', '开源'],
  },
  {
    id: 'ai-img-9',
    title: 'ComfyUI',
    description: '强大的节点式AI图像工作流',
    url: 'https://github.com/comfyanonymous/ComfyUI',
    category: 'ai-image',
    subcategory: 'AI绘画',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['AI绘画', 'ComfyUI', '工作流'],
  },
  {
    id: 'ai-img-10',
    title: 'Stable Diffusion XL',
    description: 'Stability AI最新图像生成模型',
    url: 'https://stability.ai/',
    category: 'ai-image',
    subcategory: 'AI绘画',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['AI绘画', 'SDXL', '开源'],
  },

  // ============ AI 工具 - AI视频 ============
  {
    id: 'ai-video-1',
    title: 'Runway',
    description: 'AI视频生成和编辑平台，Gen-2/Gen-3',
    url: 'https://runwayml.com/',
    category: 'ai-video',
    subcategory: 'AI视频',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['AI视频', '编辑', 'Gen-2'],
  },
  {
    id: 'ai-video-2',
    title: 'Pika',
    description: 'AI视频生成工具，支持多种风格',
    url: 'https://pika.art/',
    category: 'ai-video',
    subcategory: 'AI视频',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['AI视频', '生成', '免费'],
  },
  {
    id: 'ai-video-3',
    title: 'Sora (OpenAI)',
    description: 'OpenAI AI视频生成模型',
    url: 'https://openai.com/sora',
    category: 'ai-video',
    subcategory: 'AI视频',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['AI视频', 'Sora', 'OpenAI'],
  },
  {
    id: 'ai-video-4',
    title: 'Kling AI',
    description: '快手可灵AI视频生成',
    url: 'https://klingai.com/',
    category: 'ai-video',
    subcategory: 'AI视频',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['AI视频', '可灵', '国产'],
  },
  {
    id: 'ai-video-5',
    title: 'Luma Dream Machine',
    description: 'Luma AI视频生成工具',
    url: 'https://lumalabs.ai/dream-machine',
    category: 'ai-video',
    subcategory: 'AI视频',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['AI视频', 'Luma', '生成'],
  },
  {
    id: 'ai-video-6',
    title: 'Hailuo AI',
    description: 'MiniMax AI视频生成',
    url: 'https://hailuoai.video/',
    category: 'ai-video',
    subcategory: 'AI视频',
    type: 'free',
    hot: true,
    rating: 4.4,
    tags: ['AI视频', '海螺', '国产'],
  },
  {
    id: 'ai-video-7',
    title: 'HeyGen',
    description: 'AI数字人视频生成',
    url: 'https://heygen.com/',
    category: 'ai-video',
    subcategory: '数字人',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['AI视频', '数字人', 'HeyGen'],
  },
  {
    id: 'ai-video-8',
    title: 'D-ID',
    description: 'AI数字人创建平台',
    url: 'https://www.d-id.com/',
    category: 'ai-video',
    subcategory: '数字人',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['AI视频', '数字人', 'D-ID'],
  },

  // ============ AI 工具 - AI音乐 ============
  {
    id: 'ai-music-1',
    title: 'Suno',
    description: 'AI音乐生成工具，可以创作歌曲',
    url: 'https://suno.ai/',
    category: 'ai-music',
    subcategory: 'AI音乐',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['AI音乐', '创作', 'Suno'],
  },
  {
    id: 'ai-music-2',
    title: 'Udio',
    description: 'AI音乐生成平台，音乐质量高',
    url: 'https://www.udio.com/',
    category: 'ai-music',
    subcategory: 'AI音乐',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['AI音乐', '创作', '免费'],
  },
  {
    id: 'ai-music-3',
    title: 'ElevenLabs',
    description: 'AI语音合成和克隆',
    url: 'https://elevenlabs.io/',
    category: 'ai-music',
    subcategory: 'AI语音',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['AI语音', '克隆', '合成'],
  },
  {
    id: 'ai-music-4',
    title: 'Mubert',
    description: 'AI音乐生成背景音乐',
    url: 'https://mubert.com/',
    category: 'ai-music',
    subcategory: 'AI音乐',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['AI音乐', '背景', 'Mubert'],
  },
  {
    id: 'ai-music-5',
    title: 'Voicemaker',
    description: 'AI语音合成工具',
    url: 'https://voicemaker.in/',
    category: 'ai-music',
    subcategory: 'AI语音',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['AI语音', 'TTS', '合成'],
  },

  // ============ AI 工具 - AI编程 ============
  {
    id: 'ai-code-1',
    title: 'GitHub Copilot',
    description: 'AI编程助手，代码补全神器',
    url: 'https://github.com/features/copilot',
    category: 'ai-coding',
    subcategory: 'AI编程',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['AI编程', 'Copilot', '代码补全'],
  },
  {
    id: 'ai-code-2',
    title: 'Cursor',
    description: 'AI代码编辑器，支持多语言',
    url: 'https://cursor.sh/',
    category: 'ai-coding',
    subcategory: 'AI编程',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['AI编程', '编辑器', '免费'],
  },
  {
    id: 'ai-code-3',
    title: 'Codeium',
    description: '免费AI代码补全工具',
    url: 'https://codeium.com/',
    category: 'ai-coding',
    subcategory: 'AI编程',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['AI编程', '免费', '代码补全'],
  },
  {
    id: 'ai-code-4',
    title: 'Tabnine',
    description: 'AI代码助手，支持多种IDE',
    url: 'https://www.tabnine.com/',
    category: 'ai-coding',
    subcategory: 'AI编程',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['AI编程', 'IDE插件', '免费'],
  },
  {
    id: 'ai-code-5',
    title: 'Phind',
    description: 'AI开发者搜索引擎',
    url: 'https://www.phind.com/',
    category: 'ai-coding',
    subcategory: 'AI搜索',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['AI搜索', '开发者', '编程'],
  },
  {
    id: 'ai-code-6',
    title: 'Replit',
    description: '在线AI编程平台',
    url: 'https://replit.com/',
    category: 'ai-coding',
    subcategory: 'AI编程',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['AI编程', '在线IDE', 'Replit'],
  },
  {
    id: 'ai-code-7',
    title: 'Amazon CodeWhisperer',
    description: 'AWS AI代码助手免费版',
    url: 'https://aws.amazon.com/codewhisperer/',
    category: 'ai-coding',
    subcategory: 'AI编程',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['AI编程', 'AWS', '免费'],
  },
  {
    id: 'ai-code-8',
    title: 'Devin (Cognition)',
    description: 'AI软件工程师',
    url: 'https://cognition.ai/',
    category: 'ai-coding',
    subcategory: 'AI编程',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['AI编程', 'Devin', 'AI工程师'],
  },

  // ============ AI 工具 - 提示词 ============
  {
    id: 'ai-prompt-1',
    title: 'PromptHero',
    description: 'AI提示词搜索引擎和社区',
    url: 'https://prompthero.com/',
    category: 'ai-prompts',
    subcategory: '提示词',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['提示词', '搜索', '社区'],
  },
  {
    id: 'ai-prompt-2',
    title: 'PromptBase',
    description: 'AI提示词交易市场',
    url: 'https://promptbase.com/',
    category: 'ai-prompts',
    subcategory: '提示词',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['提示词', '市场', '付费'],
  },
  {
    id: 'ai-prompt-3',
    title: 'Public Prompts',
    description: '免费开源AI提示词库',
    url: 'https://publicprompts.art/',
    category: 'ai-prompts',
    subcategory: '提示词',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['提示词', '免费', '开源'],
  },
  {
    id: 'ai-prompt-4',
    title: 'MJ Prompt Guide',
    description: 'Midjourney官方提示词指南',
    url: 'https://docs.midjourney.com/docs/prompts',
    category: 'ai-prompts',
    subcategory: 'MJ提示词',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['Midjourney', '官方', '教程'],
  },
  {
    id: 'ai-prompt-5',
    title: 'FlowGPT',
    description: 'ChatGPT提示词分享社区',
    url: 'https://flowgpt.com/',
    category: 'ai-prompts',
    subcategory: '提示词',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['ChatGPT', '提示词', '社区'],
  },
  {
    id: 'ai-prompt-6',
    title: 'AIPRM',
    description: 'ChatGPT提示词浏览器插件',
    url: 'https://aiprm.com/',
    category: 'ai-prompts',
    subcategory: '提示词',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['ChatGPT', '插件', '提示词'],
  },
  {
    id: 'ai-prompt-7',
    title: 'Promptpal AI',
    description: 'AI提示词搜索引擎',
    url: 'https://promptpalai.com/',
    category: 'ai-prompts',
    subcategory: '提示词',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['提示词', '搜索', 'AI'],
  },

  // ============ 影视网站 ============
  {
    id: 'video-1',
    title: 'YouTube',
    description: '全球最大视频网站，免费观看',
    url: 'https://www.youtube.com/',
    category: 'video-streaming',
    subcategory: '视频网站',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['YouTube', '视频', '免费'],
  },
  {
    id: 'video-2',
    title: 'Bilibili',
    description: '国内知名视频弹幕网站',
    url: 'https://www.bilibili.com/',
    category: 'video-streaming',
    subcategory: '视频网站',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['B站', '视频', '弹幕'],
  },
  {
    id: 'video-3',
    title: 'Plex',
    description: '免费媒体服务器和播放器',
    url: 'https://www.plex.tv/',
    category: 'video-streaming',
    subcategory: '播放器',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['Plex', '媒体服务器', '免费'],
  },
  {
    id: 'video-4',
    title: 'Stremio',
    description: '免费视频聚合播放器',
    url: 'https://www.stremio.com/',
    category: 'video-streaming',
    subcategory: '播放器',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['Stremio', '播放器', '免费'],
  },
  {
    id: 'video-5',
    title: 'FilmPlus',
    description: '免费电影电视剧在线观看',
    url: 'https://filmplus.org/',
    category: 'video-streaming',
    subcategory: '影视',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['电影', '在线', '免费'],
  },
  {
    id: 'video-6',
    title: 'Soap2Day',
    description: '免费高清电影在线看',
    url: 'https://soap2day.to/',
    category: 'video-streaming',
    subcategory: '影视',
    type: 'free',
    hot: true,
    rating: 4.4,
    tags: ['电影', '在线', '免费'],
  },
  {
    id: 'video-7',
    title: '123Movies',
    description: '免费电影电视剧网站',
    url: 'https://123movie.app/',
    category: 'video-streaming',
    subcategory: '影视',
    type: 'free',
    hot: true,
    rating: 4.3,
    tags: ['电影', '在线', '免费'],
  },
  {
    id: 'video-8',
    title: 'Fmovies',
    description: '免费电影网站',
    url: 'https://fmoviesmag.com/',
    category: 'video-streaming',
    subcategory: '影视',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['电影', '在线', '免费'],
  },
  {
    id: 'video-9',
    title: 'MoviesNinja',
    description: '免费高清电影下载',
    url: 'https://moviesninja.dad/',
    category: 'video-streaming',
    subcategory: '影视',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['电影', '下载', '高清'],
  },
  {
    id: 'video-10',
    title: 'YTS',
    description: '高质量小体积电影种子',
    url: 'https://yts.mx/',
    category: 'video-streaming',
    subcategory: '影视',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['电影', '种子', 'YTS'],
  },
  {
    id: 'video-11',
    title: 'TVLogy',
    description: '在线电视直播网站',
    url: 'https://tvlogy.top/',
    category: 'video-streaming',
    subcategory: '直播',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['电视', '直播', '免费'],
  },
  {
    id: 'video-12',
    title: 'BBC iPlayer',
    description: 'BBC官方流媒体服务',
    url: 'https://www.bbc.co.uk/iplayer',
    category: 'video-streaming',
    subcategory: '流媒体',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['BBC', '英国', '直播'],
  },
  {
    id: 'video-13',
    title: 'Peacock TV',
    description: 'NBC流媒体平台',
    url: 'https://www.peacocktv.com/',
    category: 'video-streaming',
    subcategory: '流媒体',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['NBC', '美剧', '流媒体'],
  },
  {
    id: 'video-14',
    title: 'Pluto TV',
    description: '免费流媒体电视',
    url: 'https://pluto.tv/',
    category: 'video-streaming',
    subcategory: '流媒体',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['免费', '电视', '直播'],
  },
  {
    id: 'video-15',
    title: 'Tubi',
    description: '免费电影电视剧',
    url: 'https://tubi.tv/',
    category: 'video-streaming',
    subcategory: '流媒体',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['免费', '电影', '广告'],
  },

  // ============ 动漫 ============
  {
    id: 'anime-1',
    title: 'aniwave',
    description: '免费高清动漫在线观看',
    url: 'https://aniwave.to/',
    category: 'anime',
    subcategory: '动漫网站',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['动漫', '在线', '免费'],
  },
  {
    id: 'anime-2',
    title: 'aniplanet',
    description: '免费动漫流媒体',
    url: 'https://aniplanet.org/',
    category: 'anime',
    subcategory: '动漫网站',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['动漫', '流媒体', '免费'],
  },
  {
    id: 'anime-3',
    title: 'animepahe',
    description: '高质量动漫下载站',
    url: 'https://animepahe.com/',
    category: 'anime',
    subcategory: '动漫下载',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['动漫', '下载', '高质量'],
  },
  {
    id: 'anime-4',
    title: 'aniplay',
    description: '在线动漫播放',
    url: 'https://aniplay.com/',
    category: 'anime',
    subcategory: '动漫网站',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['动漫', '在线', '播放'],
  },
  {
    id: 'anime-5',
    title: 'KickAssAnime',
    description: '动漫在线观看',
    url: 'https://kickassanimes.org/',
    category: 'anime',
    subcategory: '动漫网站',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['动漫', '在线', '免费'],
  },
  {
    id: 'anime-6',
    title: 'Goku',
    description: '动漫在线观看网站',
    url: 'https://goku.nxone.com/',
    category: 'anime',
    subcategory: '动漫网站',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['动漫', '在线', 'Goku'],
  },
  {
    id: 'anime-7',
    title: 'AnimeShoujo',
    description: '少女向动漫资源',
    url: 'https://www.animeshoujo.com/',
    category: 'anime',
    subcategory: '动漫网站',
    type: 'free',
    hot: false,
    rating: 4.2,
    tags: ['动漫', '少女', '免费'],
  },
  {
    id: 'anime-8',
    title: 'Kissanime',
    description: '经典动漫网站',
    url: 'https://kissanime.com.bz/',
    category: 'anime',
    subcategory: '动漫网站',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['动漫', '经典', '在线'],
  },
  {
    id: 'anime-9',
    title: '9anime',
    description: '高清动漫在线看',
    url: 'https://9anime.to/',
    category: 'anime',
    subcategory: '动漫网站',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['动漫', '高清', '在线'],
  },
  {
    id: 'anime-10',
    title: 'ConsumeNetwork',
    description: '动漫影视综合站',
    url: 'https://consume.network/',
    category: 'anime',
    subcategory: '动漫网站',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['动漫', '综合', '免费'],
  },

  // ============ 纪录片 ============
  {
    id: 'doc-1',
    title: 'DocumentaryArea',
    description: '免费纪录片在线观看',
    url: 'https://www.documentaryarea.com/',
    category: 'documentary',
    subcategory: '纪录片',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['纪录片', '免费', '在线'],
  },
  {
    id: 'doc-2',
    title: 'Top Documentary Films',
    description: '纪录片精选网站',
    url: 'https://topdocumentaryfilms.com/',
    category: 'documentary',
    subcategory: '纪录片',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['纪录片', '精选', '免费'],
  },
  {
    id: 'doc-3',
    title: 'Thought Maybe',
    description: '独立纪录片网站',
    url: 'https://thoughtmaybe.com/',
    category: 'documentary',
    subcategory: '纪录片',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['纪录片', '独立', '免费'],
  },
  {
    id: 'doc-4',
    title: 'Viewster',
    description: '在线纪录片和动漫',
    url: 'https://www.viewster.com/',
    category: 'documentary',
    subcategory: '纪录片',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['纪录片', '动漫', '在线'],
  },
  {
    id: 'doc-5',
    title: 'ARTE',
    description: '欧洲纪录片平台',
    url: 'https://www.arte.tv/',
    category: 'documentary',
    subcategory: '纪录片',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['纪录片', '欧洲', 'ARTE'],
  },

  // ============ 游戏 ============
  {
    id: 'game-1',
    title: 'Steam',
    description: '全球最大游戏平台',
    url: 'https://store.steampowered.com/',
    category: 'gaming',
    subcategory: '游戏平台',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['Steam', '游戏', '平台'],
  },
  {
    id: 'game-2',
    title: 'Epic Games',
    description: 'Epic免费游戏每周送',
    url: 'https://store.epicgames.com/',
    category: 'gaming',
    subcategory: '游戏平台',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['Epic', '免费游戏', '平台'],
  },
  {
    id: 'game-3',
    title: 'GOG',
    description: '无DRM游戏平台',
    url: 'https://www.gog.com/',
    category: 'gaming',
    subcategory: '游戏平台',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['GOG', '无DRM', '经典游戏'],
  },
  {
    id: 'game-4',
    title: 'Riot Games',
    description: '英雄联盟、瓦洛兰特等',
    url: 'https://www.riotgames.com/',
    category: 'gaming',
    subcategory: '游戏公司',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['英雄联盟', '电竞', '免费'],
  },
  {
    id: 'game-5',
    title: 'OceanHero',
    description: '浏览器游戏聚合平台',
    url: 'https://oceanhero.gg/',
    category: 'gaming',
    subcategory: '小游戏',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['小游戏', 'HTML5', '免费'],
  },
  {
    id: 'game-6',
    title: 'itch.io',
    description: '独立游戏平台',
    url: 'https://itch.io/',
    category: 'gaming',
    subcategory: '游戏平台',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['独立游戏', '免费', '平台'],
  },
  {
    id: 'game-7',
    title: 'GG Selector',
    description: '在线游戏平台',
    url: 'https://ggselector.com/',
    category: 'gaming',
    subcategory: '在线游戏',
    type: 'free',
    hot: false,
    rating: 4.2,
    tags: ['在线游戏', '免费', '平台'],
  },
  {
    id: 'game-8',
    title: 'GameJolt',
    description: '游戏社区和平台',
    url: 'https://gamejolt.com/',
    category: 'gaming',
    subcategory: '游戏平台',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['独立游戏', '社区', '免费'],
  },
  {
    id: 'game-9',
    title: 'Roblox',
    description: '在线游戏平台',
    url: 'https://www.roblox.com/',
    category: 'gaming',
    subcategory: '游戏平台',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['Roblox', '在线', '免费'],
  },
  {
    id: 'game-10',
    title: 'Ruffle',
    description: 'Flash游戏模拟器',
    url: 'https://ruffle.rs/',
    category: 'gaming',
    subcategory: '模拟器',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['Flash', '游戏', '模拟器'],
  },
  {
    id: 'game-11',
    title: '存档发布器',
    description: '游戏存档分享',
    url: 'https://saves.thegamesdb.net/',
    category: 'gaming',
    subcategory: '游戏资源',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['存档', '分享', '游戏'],
  },
  {
    id: 'game-12',
    title: 'PCGamingWiki',
    description: 'PC游戏百科',
    url: 'https://www.pcgamingwiki.com/',
    category: 'gaming',
    subcategory: '游戏百科',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['游戏', '百科', 'PC'],
  },

  // ============ 模拟器 ============
  {
    id: 'emu-1',
    title: 'Ryujinx',
    description: '开源Switch模拟器',
    url: 'https://ryujinx.org/',
    category: 'emulator',
    subcategory: '模拟器',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['Switch', '模拟器', '开源'],
  },
  {
    id: 'emu-2',
    title: 'PCSX2',
    description: 'PS2模拟器',
    url: 'https://pcsx2.net/',
    category: 'emulator',
    subcategory: '模拟器',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['PS2', '模拟器', '开源'],
  },
  {
    id: 'emu-3',
    title: 'Dolphin',
    description: 'Wii/GameCube模拟器',
    url: 'https://dolphin-emu.org/',
    category: 'emulator',
    subcategory: '模拟器',
    type: 'free',
    hot: false,
    rating: 4.7,
    tags: ['Wii', '模拟器', '开源'],
  },
  {
    id: 'emu-4',
    title: 'RetroArch',
    description: '多合一复古游戏模拟器',
    url: 'https://www.retroarch.com/',
    category: 'emulator',
    subcategory: '模拟器',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['复古', '模拟器', '聚合'],
  },
  {
    id: 'emu-5',
    title: 'PPSSPP',
    description: 'PSP模拟器',
    url: 'https://www.ppsspp.org/',
    category: 'emulator',
    subcategory: '模拟器',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['PSP', '模拟器', '开源'],
  },
  {
    id: 'emu-6',
    title: 'Yuzu',
    description: 'Switch模拟器（已停止开发）',
    url: 'https://yuzu-emu.org/',
    category: 'emulator',
    subcategory: '模拟器',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['Switch', 'Yuzu', '模拟器'],
  },
  {
    id: 'emu-7',
    title: 'Cemu',
    description: 'Wii U模拟器',
    url: 'https://cemu.info/',
    category: 'emulator',
    subcategory: '模拟器',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['WiiU', '模拟器', 'Cemu'],
  },
  {
    id: 'emu-8',
    title: 'RPCS3',
    description: 'PS3模拟器',
    url: 'https://rpcs3.net/',
    category: 'emulator',
    subcategory: '模拟器',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['PS3', '模拟器', '开源'],
  },
  {
    id: 'emu-9',
    title: 'MAME',
    description: '街机模拟器',
    url: 'https://www.mamedev.org/',
    category: 'emulator',
    subcategory: '模拟器',
    type: 'free',
    hot: false,
    rating: 4.7,
    tags: ['街机', '模拟器', 'MAME'],
  },
  {
    id: 'emu-10',
    title: 'DeSmuME',
    description: 'NDS模拟器',
    url: 'https://desmume.org/',
    category: 'emulator',
    subcategory: '模拟器',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['NDS', '模拟器', '开源'],
  },

  // ============ 电子书 ============
  {
    id: 'ebook-1',
    title: 'Z-Library',
    description: '全球最大免费电子书库',
    url: 'https://singlelogin.se/',
    category: 'ebook',
    subcategory: '电子书',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['电子书', '免费', 'Z-Library'],
  },
  {
    id: 'ebook-2',
    title: 'Anna\'s Archive',
    description: 'Z-Library镜像和备份',
    url: 'https://annas-archive.org/',
    category: 'ebook',
    subcategory: '电子书',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['电子书', '镜像', '备份'],
  },
  {
    id: 'ebook-3',
    title: 'LibGen',
    description: '经典电子书下载站',
    url: 'https://libgen.is/',
    category: 'ebook',
    subcategory: '电子书',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['电子书', 'LibGen', '免费'],
  },
  {
    id: 'ebook-4',
    title: 'Project Gutenberg',
    description: '公共领域电子书',
    url: 'https://www.gutenberg.org/',
    category: 'ebook',
    subcategory: '公版书',
    type: 'free',
    hot: false,
    rating: 4.8,
    tags: ['公版书', '免费', '经典'],
  },
  {
    id: 'ebook-5',
    title: 'Standard Ebooks',
    description: '高质量公版电子书',
    url: 'https://standardebooks.org/',
    category: 'ebook',
    subcategory: '公版书',
    type: 'free',
    hot: false,
    rating: 4.7,
    tags: ['公版书', '高质量', '排版精美'],
  },
  {
    id: 'ebook-6',
    title: 'Open Library',
    description: '互联网档案馆电子书',
    url: 'https://openlibrary.org/',
    category: 'ebook',
    subcategory: '电子书',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['电子书', '图书馆', '免费'],
  },
  {
    id: 'ebook-7',
    title: 'BookFI',
    description: '俄语电子书资源',
    url: 'https://bookfi.org/',
    category: 'ebook',
    subcategory: '电子书',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['电子书', '俄语', '免费'],
  },
  {
    id: 'ebook-8',
    title: 'Library Genesis',
    description: '科学文献电子书',
    url: 'https://libgen.li/',
    category: 'ebook',
    subcategory: '学术',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['学术', '论文', '电子书'],
  },
  {
    id: 'ebook-9',
    title: 'Archive.org',
    description: '互联网档案馆',
    url: 'https://archive.org/',
    category: 'ebook',
    subcategory: '归档',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['归档', '免费', '资料库'],
  },
  {
    id: 'ebook-10',
    title: 'ManyBooks',
    description: '免费电子书下载',
    url: 'https://manybooks.net/',
    category: 'ebook',
    subcategory: '电子书',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['电子书', '下载', '免费'],
  },
  {
    id: 'ebook-11',
    title: 'BookBoon',
    description: 'PDF电子书下载',
    url: 'https://bookboon.com/',
    category: 'ebook',
    subcategory: '电子书',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['PDF', '电子书', '免费'],
  },
  {
    id: 'ebook-12',
    title: 'FreeComputerBooks',
    description: '计算机电子书',
    url: 'https://freecomputerbooks.com/',
    category: 'ebook',
    subcategory: '技术书',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['计算机', '电子书', '免费'],
  },
  {
    id: 'ebook-13',
    title: 'MangaDex',
    description: '在线漫画阅读',
    url: 'https://mangadex.org/',
    category: 'ebook',
    subcategory: '漫画',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['漫画', '在线', 'MangaDex'],
  },
  {
    id: 'ebook-14',
    title: 'ReadAnyBook',
    description: '免费在线书籍',
    url: 'https://readanybook.com/',
    category: 'ebook',
    subcategory: '电子书',
    type: 'free',
    hot: false,
    rating: 4.2,
    tags: ['电子书', '在线', '免费'],
  },
  {
    id: 'ebook-15',
    title: 'PDFDrive',
    description: 'PDF搜索和下载',
    url: 'https://www.pdfdrive.com/',
    category: 'ebook',
    subcategory: 'PDF',
    type: 'free',
    hot: true,
    rating: 4.4,
    tags: ['PDF', '搜索', '下载'],
  },

  // ============ 有声书 ============
  {
    id: 'audiobook-1',
    title: 'Librivox',
    description: '公版书有声书',
    url: 'https://librivox.org/',
    category: 'audiobook',
    subcategory: '有声书',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['有声书', '公版', '免费'],
  },
  {
    id: 'audiobook-2',
    title: 'Lit2Go',
    description: '在线有声书',
    url: 'https://etc.usf.edu/lit2go/',
    category: 'audiobook',
    subcategory: '有声书',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['有声书', '在线', '教育'],
  },
  {
    id: 'audiobook-3',
    title: 'AudioBook Sync',
    description: '免费有声书活动',
    url: 'https://www.audiobookedsync.com/',
    category: 'audiobook',
    subcategory: '有声书',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['有声书', '活动', '免费'],
  },
  {
    id: 'audiobook-4',
    title: 'StoryNory',
    description: '免费有声书故事',
    url: 'https://storynory.com/',
    category: 'audiobook',
    subcategory: '有声书',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['有声书', '故事', '儿童'],
  },
  {
    id: 'audiobook-5',
    title: ' Loyal Books',
    description: '免费有声书和电子书',
    url: 'https://www.loyalbooks.com/',
    category: 'audiobook',
    subcategory: '有声书',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['有声书', '电子书', '免费'],
  },

  // ============ 音乐 ============
  {
    id: 'music-1',
    title: 'Spotify',
    description: '全球最大音乐流媒体',
    url: 'https://spotify.com/',
    category: 'music',
    subcategory: '音乐',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['Spotify', '音乐', '流媒体'],
  },
  {
    id: 'music-2',
    title: 'SoundCloud',
    description: '音乐分享平台',
    url: 'https://soundcloud.com/',
    category: 'music',
    subcategory: '音乐',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['SoundCloud', '音乐', '分享'],
  },
  {
    id: 'music-3',
    title: 'Bandcamp',
    description: '独立音乐平台',
    url: 'https://bandcamp.com/',
    category: 'music',
    subcategory: '音乐',
    type: 'free',
    hot: false,
    rating: 4.7,
    tags: ['Bandcamp', '独立音乐', '购买'],
  },
  {
    id: 'music-4',
    title: 'YouTube Music',
    description: 'YouTube音乐服务',
    url: 'https://music.youtube.com/',
    category: 'music',
    subcategory: '音乐',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['YouTube', '音乐', '免费'],
  },
  {
    id: 'music-5',
    title: 'Musopen',
    description: '古典音乐免费听',
    url: 'https://musopen.org/',
    category: 'music',
    subcategory: '古典音乐',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['古典音乐', '免费', '公版'],
  },
  {
    id: 'music-6',
    title: 'Jamendo',
    description: '独立音乐平台',
    url: 'https://www.jamendo.com/',
    category: 'music',
    subcategory: '音乐',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['独立音乐', '免费', 'Jamendo'],
  },
  {
    id: 'music-7',
    title: 'Audiomack',
    description: '音乐流媒体和下载',
    url: 'https://audiomack.com/',
    category: 'music',
    subcategory: '音乐',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['音乐', '下载', '流媒体'],
  },
  {
    id: 'music-8',
    title: 'PureVolume',
    description: '独立音乐平台',
    url: 'https://purevolume.com/',
    category: 'music',
    subcategory: '音乐',
    type: 'free',
    hot: false,
    rating: 4.2,
    tags: ['独立音乐', '平台', '免费'],
  },

  // ============ 播客 ============
  {
    id: 'podcast-1',
    title: 'Spotify Podcasts',
    description: 'Spotify播客服务',
    url: 'https://spotify.com/',
    category: 'podcast',
    subcategory: '播客',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['播客', 'Spotify', '免费'],
  },
  {
    id: 'podcast-2',
    title: 'Pocket Casts',
    description: '播客播放器',
    url: 'https://pocketcasts.com/',
    category: 'podcast',
    subcategory: '播客',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['播客', '播放器', '免费'],
  },
  {
    id: 'podcast-3',
    title: 'AntennaPod',
    description: '开源播客应用',
    url: 'https://antennapod.org/',
    category: 'podcast',
    subcategory: '播客',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['播客', '开源', 'Android'],
  },
  {
    id: 'podcast-4',
    title: 'PodcastAddict',
    description: '安卓播客应用',
    url: 'https://podcastaddict.com/',
    category: 'podcast',
    subcategory: '播客',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['播客', 'Android', '应用'],
  },
  {
    id: 'podcast-5',
    title: 'Podbean',
    description: '播客托管平台',
    url: 'https://www.podbean.com/',
    category: 'podcast',
    subcategory: '播客',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['播客', '托管', '平台'],
  },

  // ============ 在线课程 ============
  {
    id: 'course-1',
    title: 'Coursera',
    description: '全球知名在线课程平台',
    url: 'https://www.coursera.org/',
    category: 'courses',
    subcategory: 'MOOC',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['Coursera', 'MOOC', '证书'],
  },
  {
    id: 'course-2',
    title: 'edX',
    description: 'MIT和哈佛创办的MOOC平台',
    url: 'https://www.edx.org/',
    category: 'courses',
    subcategory: 'MOOC',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['edX', 'MOOC', '顶尖名校'],
  },
  {
    id: 'course-3',
    title: 'Khan Academy',
    description: '免费在线教育平台',
    url: 'https://www.khanacademy.org/',
    category: 'courses',
    subcategory: 'K12',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['可汗学院', '免费', '教育'],
  },
  {
    id: 'course-4',
    title: 'MIT OpenCourseWare',
    description: 'MIT开放课程',
    url: 'https://ocw.mit.edu/',
    category: 'courses',
    subcategory: 'MOOC',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['MIT', '开放课程', '免费'],
  },
  {
    id: 'course-5',
    title: 'Class Central',
    description: 'MOOC课程聚合搜索',
    url: 'https://www.classcentral.com/',
    category: 'courses',
    subcategory: 'MOOC',
    type: 'free',
    hot: false,
    rating: 4.7,
    tags: ['MOOC', '聚合', '搜索'],
  },
  {
    id: 'course-6',
    title: 'Alison',
    description: '免费在线课程平台',
    url: 'https://alison.com/',
    category: 'courses',
    subcategory: 'MOOC',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['Alison', '免费', '证书'],
  },
  {
    id: 'course-7',
    title: 'OpenLearn',
    description: '英国开放大学免费课程',
    url: 'https://www.open.edu/openlearn/',
    category: 'courses',
    subcategory: 'MOOC',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['OpenLearn', '免费', '英国'],
  },
  {
    id: 'course-8',
    title: 'Duolingo',
    description: '免费语言学习',
    url: 'https://www.duolingo.com/',
    category: 'courses',
    subcategory: '语言',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['语言', '免费', '学习'],
  },
  {
    id: 'course-9',
    title: 'Codecademy',
    description: '编程学习平台',
    url: 'https://www.codecademy.com/',
    category: 'courses',
    subcategory: '编程',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['编程', '学习', 'Codecademy'],
  },
  {
    id: 'course-10',
    title: 'Udemy Free',
    description: '免费Udemy课程',
    url: 'https:// udemy.com/course/freebies/',
    category: 'courses',
    subcategory: 'MOOC',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['Udemy', '免费', '课程'],
  },
  {
    id: 'course-11',
    title: 'Skillshare',
    description: '创意技能学习平台',
    url: 'https://skillshare.com/',
    category: 'courses',
    subcategory: '技能',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['技能', '创意', '学习'],
  },
  {
    id: 'course-12',
    title: '365 Data Science',
    description: '数据科学课程',
    url: 'https://365datascience.com/',
    category: 'courses',
    subcategory: '数据',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['数据科学', '免费', '课程'],
  },
  {
    id: 'course-13',
    title: 'O\'Reilly Learning',
    description: '技术书籍和课程',
    url: 'https://www.oreilly.com/',
    category: 'courses',
    subcategory: '技术',
    type: 'free',
    hot: false,
    rating: 4.7,
    tags: ['技术', '书籍', '课程'],
  },

  // ============ 下载工具 ============
  {
    id: 'dl-1',
    title: 'qBittorrent',
    description: '开源BitTorrent客户端',
    url: 'https://www.qbittorrent.org/',
    category: 'torrenting',
    subcategory: '下载',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['qBittorrent', '下载', '开源'],
  },
  {
    id: 'dl-2',
    title: 'Ninite',
    description: '一次性安装多个软件',
    url: 'https://ninite.com/',
    category: 'torrenting',
    subcategory: '软件',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['软件', '批量', '安装'],
  },
  {
    id: 'dl-3',
    title: 'FileHorse',
    description: 'Windows软件下载站',
    url: 'https://www.filehorse.com/',
    category: 'torrenting',
    subcategory: '下载',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['Windows', '软件', '下载'],
  },
  {
    id: 'dl-4',
    title: 'Softpedia',
    description: '软件和驱动下载',
    url: 'https://www.softpedia.com/',
    category: 'torrenting',
    subcategory: '下载',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['软件', '驱动', '下载'],
  },
  {
    id: 'dl-5',
    title: '1337x',
    description: '磁力链接搜索引擎',
    url: 'https://1337x.to/',
    category: 'torrenting',
    subcategory: '种子',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['种子', '搜索', '1337x'],
  },
  {
    id: 'dl-6',
    title: 'RARBG',
    description: '知名种子站',
    url: 'https://rarbg.to/',
    category: 'torrenting',
    subcategory: '种子',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['种子', 'RARBG', '下载'],
  },
  {
    id: 'dl-7',
    title: ' TorrentGalaxy',
    description: '种子下载站',
    url: 'https://torrentgalaxy.to/',
    category: 'torrenting',
    subcategory: '种子',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['种子', '下载', 'TGx'],
  },
  {
    id: 'dl-8',
    title: 'Library Genesis',
    description: '学术文献下载',
    url: 'https://libgen.li/',
    category: 'torrenting',
    subcategory: '学术',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['学术', '论文', '下载'],
  },
  {
    id: 'dl-9',
    title: 'Academia Torrents',
    description: '学术数据集分享',
    url: 'https://academictorrents.com/',
    category: 'torrenting',
    subcategory: '学术',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['学术', '数据集', '分享'],
  },

  // ============ 效率工具 ============
  {
    id: 'tool-1',
    title: 'Notion',
    description: '全能笔记和知识管理',
    url: 'https://www.notion.so/',
    category: 'tools',
    subcategory: '效率',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['Notion', '笔记', '知识管理'],
  },
  {
    id: 'tool-2',
    title: 'Obsidian',
    description: '本地Markdown笔记',
    url: 'https://obsidian.md/',
    category: 'tools',
    subcategory: '笔记',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['Obsidian', 'Markdown', '本地'],
  },
  {
    id: 'tool-3',
    title: 'Canva',
    description: '在线设计工具',
    url: 'https://www.canva.com/',
    category: 'tools',
    subcategory: '设计',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['Canva', '设计', '免费'],
  },
  {
    id: 'tool-4',
    title: 'Figma',
    description: '在线协作设计工具',
    url: 'https://www.figma.com/',
    category: 'tools',
    subcategory: '设计',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['Figma', 'UI设计', '协作'],
  },
  {
    id: 'tool-5',
    title: 'Visual Studio Code',
    description: '最流行的代码编辑器',
    url: 'https://code.visualstudio.com/',
    category: 'tools',
    subcategory: '编程',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['VSCode', '编辑器', '免费'],
  },
  {
    id: 'tool-6',
    title: 'Bitwarden',
    description: '开源密码管理器',
    url: 'https://bitwarden.com/',
    category: 'tools',
    subcategory: '安全',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['Bitwarden', '开源', '密码'],
  },
  {
    id: 'tool-7',
    title: 'Google Docs',
    description: '在线文档协作',
    url: 'https://docs.google.com/',
    category: 'tools',
    subcategory: '办公',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['Google', '文档', '协作'],
  },
  {
    id: 'tool-8',
    title: 'Convertio',
    description: '在线文件转换器',
    url: 'https://convertio.co/',
    category: 'tools',
    subcategory: '转换',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['转换', '格式', '在线'],
  },
  {
    id: 'tool-9',
    title: 'Smallpdf',
    description: 'PDF处理工具',
    url: 'https://smallpdf.com/',
    category: 'tools',
    subcategory: 'PDF',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['PDF', '处理', '免费'],
  },
  {
    id: 'tool-10',
    title: 'Wolfram Alpha',
    description: '计算知识引擎',
    url: 'https://www.wolframalpha.com/',
    category: 'tools',
    subcategory: '计算',
    type: 'free',
    hot: false,
    rating: 4.8,
    tags: ['计算', '知识', 'Wolfram'],
  },
  {
    id: 'tool-11',
    title: 'Photopea',
    description: '在线PS替代品',
    url: 'https://www.photopea.com/',
    category: 'tools',
    subcategory: '设计',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['PS', '在线', '图片编辑'],
  },
  {
    id: 'tool-12',
    title: 'RemoveBG',
    description: 'AI一键去背景',
    url: 'https://www.remove.bg/',
    category: 'tools',
    subcategory: '图片',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['AI', '去背景', '免费'],
  },
  {
    id: 'tool-13',
    title: '10minutemail',
    description: '临时邮箱',
    url: 'https://10minutemail.com/',
    category: 'tools',
    subcategory: '临时',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['临时邮箱', '匿名', '免费'],
  },
  {
    id: 'tool-14',
    title: 'Base64 Decode',
    description: 'Base64编码解码',
    url: 'https://www.base64decode.org/',
    category: 'tools',
    subcategory: '编码',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['Base64', '编码', '工具'],
  },

  // ============ 云存储 ============
  {
    id: 'cloud-1',
    title: 'Google Drive',
    description: 'Google云端硬盘15GB免费',
    url: 'https://drive.google.com/',
    category: 'storage',
    subcategory: '云盘',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['Google', '云盘', '免费'],
  },
  {
    id: 'cloud-2',
    title: 'Dropbox',
    description: '云存储服务',
    url: 'https://www.dropbox.com/',
    category: 'storage',
    subcategory: '云盘',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['Dropbox', '云盘', '免费'],
  },
  {
    id: 'cloud-3',
    title: 'MEGA',
    description: '端到端加密云存储',
    url: 'https://mega.io/',
    category: 'storage',
    subcategory: '云盘',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['MEGA', '加密', '云盘'],
  },
  {
    id: 'cloud-4',
    title: 'OneDrive',
    description: '微软云存储服务',
    url: 'https://onedrive.live.com/',
    category: 'storage',
    subcategory: '云盘',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['OneDrive', '微软', '云盘'],
  },
  {
    id: 'cloud-5',
    title: 'pCloud',
    description: '云存储服务',
    url: 'https://www.pcloud.com/',
    category: 'storage',
    subcategory: '云盘',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['pCloud', '云盘', '免费'],
  },
  {
    id: 'cloud-6',
    title: 'Pixeldrain',
    description: '免费文件分享',
    url: 'https://pixeldrain.com/',
    category: 'storage',
    subcategory: '文件分享',
    type: 'free',
    hot: false,
    rating: 4.3,
    tags: ['文件', '分享', '免费'],
  },
  {
    id: 'cloud-7',
    title: 'File.io',
    description: '一次性文件分享',
    url: 'https://www.file.io/',
    category: 'storage',
    subcategory: '文件分享',
    type: 'free',
    hot: false,
    rating: 4.2,
    tags: ['文件', '分享', '临时'],
  },

  // ============ 手机APP ============
  {
    id: 'mobile-1',
    title: 'Aurora Store',
    description: 'Google Play替代品',
    url: 'https://auroraoss.com/',
    category: 'mobile',
    subcategory: '应用商店',
    type: 'free',
    hot: true,
    rating: 4.6,
    tags: ['Android', '应用', 'Google Play'],
  },
  {
    id: 'mobile-2',
    title: 'APKMirror',
    description: 'APK下载网站',
    url: 'https://www.apkmirror.com/',
    category: 'mobile',
    subcategory: 'APK',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['APK', 'Android', '下载'],
  },
  {
    id: 'mobile-3',
    title: 'APKPure',
    description: 'APK应用下载',
    url: 'https://apkpure.com/',
    category: 'mobile',
    subcategory: 'APK',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['APK', 'Android', '下载'],
  },
  {
    id: 'mobile-4',
    title: 'F-Droid',
    description: '开源Android应用商店',
    url: 'https://f-droid.org/',
    category: 'mobile',
    subcategory: '应用商店',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['开源', 'Android', 'F-Droid'],
  },
  {
    id: 'mobile-5',
    title: 'S适当的Droid',
    description: '已root设备的应用',
    url: 'https://letsgodigital.org/',
    category: 'mobile',
    subcategory: '应用',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['Android', 'root', '应用'],
  },
  {
    id: 'mobile-6',
    title: 'Stremio',
    description: '视频聚合APP',
    url: 'https://www.stremio.com/',
    category: 'mobile',
    subcategory: '视频',
    type: 'free',
    hot: true,
    rating: 4.5,
    tags: ['视频', 'APP', 'Stremio'],
  },
  {
    id: 'mobile-7',
    title: 'NewPipe',
    description: 'YouTube第三方APP',
    url: 'https://newpipe.net/',
    category: 'mobile',
    subcategory: '视频',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['YouTube', 'APP', '第三方'],
  },
  {
    id: 'mobile-8',
    title: 'Sync for Reddit',
    description: 'Reddit第三方APP',
    url: 'https://play.google.com/store/apps/details?id=com.laurencedawson.reddit_sync',
    category: 'mobile',
    subcategory: '社交',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['Reddit', 'APP', '第三方'],
  },

  // ============ 资源归档 ============
  {
    id: 'archive-1',
    title: 'Archive.org',
    description: '互联网档案馆',
    url: 'https://archive.org/',
    category: 'archive',
    subcategory: '归档',
    type: 'free',
    hot: true,
    rating: 4.9,
    tags: ['归档', '免费', '资料库'],
  },
  {
    id: 'archive-2',
    title: 'Wayback Machine',
    description: '网页历史存档',
    url: 'https://web.archive.org/',
    category: 'archive',
    subcategory: '网页',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['网页', '历史', '存档'],
  },
  {
    id: 'archive-3',
    title: 'Google Ngram',
    description: '书籍词频统计',
    url: 'https://books.google.com/ngrams',
    category: 'archive',
    subcategory: '书籍',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['书籍', '统计', 'Google'],
  },
  {
    id: 'archive-4',
    title: 'Dictionaries',
    description: '多语言词典',
    url: 'https://dictionaries.today/',
    category: 'archive',
    subcategory: '词典',
    type: 'free',
    hot: false,
    rating: 4.4,
    tags: ['词典', '语言', '免费'],
  },
  {
    id: 'archive-5',
    title: 'Just Free Books',
    description: '公版书搜索引擎',
    url: 'https://www.justfreebooks.info/',
    category: 'archive',
    subcategory: '书籍',
    type: 'free',
    hot: false,
    rating: 4.5,
    tags: ['公版书', '搜索', '免费'],
  },
  {
    id: 'archive-6',
    title: 'Google Scholar',
    description: '学术论文搜索',
    url: 'https://scholar.google.com/',
    category: 'archive',
    subcategory: '学术',
    type: 'free',
    hot: true,
    rating: 4.8,
    tags: ['学术', '论文', 'Google'],
  },
  {
    id: 'archive-7',
    title: 'Sci-Hub',
    description: '学术论文下载',
    url: 'https://www.sci-hub.se/',
    category: 'archive',
    subcategory: '学术',
    type: 'free',
    hot: true,
    rating: 4.7,
    tags: ['学术', '论文', '下载'],
  },
  {
    id: 'archive-8',
    title: 'Semantic Scholar',
    description: 'AI学术搜索',
    url: 'https://www.semanticscholar.org/',
    category: 'archive',
    subcategory: '学术',
    type: 'free',
    hot: false,
    rating: 4.6,
    tags: ['学术', 'AI', '搜索'],
  },
];

// 按分类分组获取资源
export function getResourcesByCategory(categoryId: string): Resource[] {
  if (categoryId === 'all') return resources;
  return resources.filter(r => r.category === categoryId);
}

// 搜索资源
export function searchResources(query: string): Resource[] {
  const lowerQuery = query.toLowerCase();
  return resources.filter(r => 
    r.title.toLowerCase().includes(lowerQuery) ||
    r.description.toLowerCase().includes(lowerQuery) ||
    r.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
}

// 获取热门资源
export function getHotResources(limit = 10): Resource[] {
  return resources.filter(r => r.hot).slice(0, limit);
}
